language: python
python:
 - "2.7"
sudo: required
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install libpcap-dev -y
 - sudo apt-get install -y build-essential libnetfilter-queue-dev
 - sudo apt-get -y install python-qt4 python-scapy python-nmap

sudo: required
install:
 - sudo pip install -r requirements.txt
 - sudo chmod +x installer.sh
 - sudo ./installer.sh --install

script: exit 0
